dataformCoreVersion: 3.0.38
defaultProject: drawingfire-b72a8
defaultDataset: dataform
vars: {
    "tableDescription": "something amazing",
    "dummyColumnValue": "43"
}
defaultAssertionDataset: dataform_assertions
defaultNotebookRuntimeOptions:
  outputBucket: "gs://dataform-notebooks"